# Generated by Django 3.0 on 2021-07-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
